//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlMappingTaskPane.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlMappingTaskPane.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Add New Part...).
        /// </summary>
        internal static string AddNewDataSource {
            get {
                return ResourceManager.GetString("AddNewDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        internal static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Banner {
            get {
                object obj = ResourceManager.GetObject("Banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CData Section.
        /// </summary>
        internal static string CDATA {
            get {
                return ResourceManager.GetString("CDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The friendly name for this custom XML part could not be changed..
        /// </summary>
        internal static string ChangePartNameErrorMessage {
            get {
                return ResourceManager.GetString("ChangePartNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete XML Document.
        /// </summary>
        internal static string CompleteXMLDocument {
            get {
                return ResourceManager.GetString("CompleteXMLDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core File Properties.
        /// </summary>
        internal static string CoreFilePropertiesName {
            get {
                return ResourceManager.GetString("CoreFilePropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Page Properties.
        /// </summary>
        internal static string CoverPagePropertiesName {
            get {
                return ResourceManager.GetString("CoverPagePropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here and enter a date..
        /// </summary>
        internal static string DatePlaceholder {
            get {
                return ResourceManager.GetString("DatePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this node will affect any controls in your document that are bound to it. Are you sure?.
        /// </summary>
        internal static string DeleteNodeMessage {
            get {
                return ResourceManager.GetString("DeleteNodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this data source will affect any content controls in your document that are bound to it.
        ///
        ///Are you sure you want to delete it?.
        /// </summary>
        internal static string DeletePartMessage {
            get {
                return ResourceManager.GetString("DeletePartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Mapping Task Pane.
        /// </summary>
        internal static string DialogTitle {
            get {
                return ResourceManager.GetString("DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose....
        /// </summary>
        internal static string DropDownPlaceholder {
            get {
                return ResourceManager.GetString("DropDownPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        internal static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A combo box content control cannot be applied to the current selection.
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorAddComboBox {
            get {
                return ResourceManager.GetString("ErrorAddComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A date picker content control cannot be applied to the current selection.
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorAddDate {
            get {
                return ResourceManager.GetString("ErrorAddDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A drop-down list content control cannot be applied to the current selection.
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorAddDropDown {
            get {
                return ResourceManager.GetString("ErrorAddDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This node could not be added:
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorAddingNode {
            get {
                return ResourceManager.GetString("ErrorAddingNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A picture content control cannot be applied to the current selection.
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorAddPicture {
            get {
                return ResourceManager.GetString("ErrorAddPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A plain text content control cannot be applied to the current selection.
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorAddPlainText {
            get {
                return ResourceManager.GetString("ErrorAddPlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected data source could not be deleted:
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorDeletePart {
            get {
                return ResourceManager.GetString("ErrorDeletePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This node could not be deleted:
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorDeletingNode {
            get {
                return ResourceManager.GetString("ErrorDeletingNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element or attribute must have a non-empty name..
        /// </summary>
        internal static string ErrorNoName {
            get {
                return ResourceManager.GetString("ErrorNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This XML file could not be added: 
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorOnPartAdd {
            get {
                return ResourceManager.GetString("ErrorOnPartAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text node could not be renamed:
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorRenamingNode {
            get {
                return ResourceManager.GetString("ErrorRenamingNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your updated settings could not be saved. Any changes will be lost..
        /// </summary>
        internal static string ErrorSaveSettings {
            get {
                return ResourceManager.GetString("ErrorSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended File Properties.
        /// </summary>
        internal static string ExtendedFilePropertiesName {
            get {
                return ResourceManager.GetString("ExtendedFilePropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file could not be located..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file specified does not contain valid XML:
        ///
        ///{0}.
        /// </summary>
        internal static string FileNotValidXml {
            get {
                return ResourceManager.GetString("FileNotValidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Line {
            get {
                object obj = ResourceManager.GetObject("Line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading...
        ///{0}%.
        /// </summary>
        internal static string LoadingMessageWithPercentage {
            get {
                return ResourceManager.GetString("LoadingMessageWithPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1033.
        /// </summary>
        internal static string Locale {
            get {
                return ResourceManager.GetString("Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        internal static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no namespace).
        /// </summary>
        internal static string NoNamespace {
            get {
                return ResourceManager.GetString("NoNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string NumberedItem {
            get {
                return ResourceManager.GetString("NumberedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to enter text..
        /// </summary>
        internal static string PlainTextPlaceholder {
            get {
                return ResourceManager.GetString("PlainTextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix Mappings.
        /// </summary>
        internal static string Prefixes {
            get {
                return ResourceManager.GetString("Prefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Instruction.
        /// </summary>
        internal static string ProcessingInstruction {
            get {
                return ResourceManager.GetString("ProcessingInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonIcon {
            get {
                object obj = ResourceManager.GetObject("RibbonIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string specified does not contain valid XML:
        ///
        ///{0}.
        /// </summary>
        internal static string StringNotValidXml {
            get {
                return ResourceManager.GetString("StringNotValidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Mapping.
        /// </summary>
        internal static string TaskPaneName {
            get {
                return ResourceManager.GetString("TaskPaneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string XML {
            get {
                return ResourceManager.GetString("XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPath.
        /// </summary>
        internal static string XPath {
            get {
                return ResourceManager.GetString("XPath", resourceCulture);
            }
        }
    }
}
